all: Prob2Semaphore Prob2CondVar
Prob2Semaphore:
	gcc prob2semaphore.c -o prob2semaphore -lpthread -w
Prob2CondVar:
	gcc prob2condVar.c -o prob2condVar -lpthread -w
clean:
	rm prob2semaphore prob2condVar
